#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c="clear"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -al"
alias l="ls -lh"
alias t="tmux"
